// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Result from "@rescript/core/src/Core__Result.res.mjs";

function a() {
  console.log(Core__Result.map({
            TAG: "Ok",
            _0: 123
          }, (function (x) {
              console.log(x);
              return 456;
            })));
}

export {
  a ,
}
/* No side effect */
